export default {
	DENY_ANY_OTHER_LINKS: 'DENY_ANY_OTHER_LINKS',
	DENY_PHOTO: 'DENY_PHOTO',
	DENY_SEX_TEXT_CONTENT: 'DENY_SEX_TEXT_CONTENT',
	DENY_STICKERS: 'DENY_STICKERS',
	DENY_SWEARING_TEXT_CONTENT: 'DENY_SWEARING_TEXT_CONTENT',
	DENY_TEXT: 'DENY_TEXT',
	DENY_VIDEO: 'DENY_VIDEO',
	DENY_YOUTUBE_LINKS: 'DENY_YOUTUBE_LINKS',
}