export default {
	Blocked: 'blocked',
	ChannelBanAdd: 'channelBanAdd',
	ChannelBanAdd: 'channelBanRemove',
	ChannelCreate: 'channelCreate',
	ChannelDelete: 'channelDelete',
	ChannelMemberAdd: 'channelMemberAdd',
	// ChannelMemberRemove: 'channelMemberRemove',
	ChannelUpdate: 'channelUpdate',
	ClientReady: 'ready',
	Debug: 'debug',
	Error: 'error',
	FriendRequestCreate: 'friendRequestCreate',
	// FriendRequestDelete: 'friendRequestDelete',
	GiftMessageCreate: 'giftMessageCreate',
	MessageCreate: 'messageCreate',
	MessageDelete: 'messageDelete',
	MessageReactionAdd: 'messageReactionAdd',
	MessageUpdate: 'messageUpdate',
	Notification: 'notification',
	Ping: 'ping',
	Raw: 'raw',
	Unblocked: 'unblocked',
	UserBlocked: 'userBlocked',
	UserUnblocked: 'userUnblocked',
	Warn: 'warn'
}